default: &default
  SECRET_KEY: 'SECRET_KEY'
  TEMPLATES_AUTO_RELOAD: true
  DEBUG: true
  ENV: ''
  SEND_FILE_MAX_AGE_DEFAULT: 0
  ASSETS_DEBUG: false

development:
  <<: *default


production:
  <<: *default