default: &default
  APP_NAME: 'Fire'
  SECRET_KEY: 'SECRET_KEY'
  TEMPLATES_AUTO_RELOAD: true
  DEBUG: true
  ENV: ''
  SEND_FILE_MAX_AGE_DEFAULT: 0
  ASSETS_DEBUG: false
  SQLALCHEMY_DATABASE_URI: sqlite:///testing.db
  SQLALCHEMY_TRACK_MODIFICATIONS: false

development:
  <<: *default


production:
  <<: *default